# Form implementation generated from reading ui file 'C:\Users\admin\PycharmProjects\K234111E\Chapter6\Ex_127\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 20, 721, 421))
        self.tableWidget.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 127);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButtonRefresh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRefresh.setGeometry(QtCore.QRect(180, 460, 131, 41))
        self.pushButtonRefresh.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 255);")
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAdd.setGeometry(QtCore.QRect(250, 510, 131, 41))
        self.pushButtonAdd.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 255);")
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDelete.setGeometry(QtCore.QRect(330, 460, 131, 41))
        self.pushButtonDelete.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 255);")
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonSort = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSort.setGeometry(QtCore.QRect(530, 510, 131, 41))
        self.pushButtonSort.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 255);")
        self.pushButtonSort.setObjectName("pushButtonSort")
        self.pushButtonGenerate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonGenerate.setGeometry(QtCore.QRect(490, 460, 131, 41))
        self.pushButtonGenerate.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 255);")
        self.pushButtonGenerate.setObjectName("pushButtonGenerate")
        self.pushButtonAddUSD = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAddUSD.setGeometry(QtCore.QRect(390, 510, 131, 41))
        self.pushButtonAddUSD.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 255);")
        self.pushButtonAddUSD.setObjectName("pushButtonAddUSD")
        self.pushButtonGbyG = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonGbyG.setGeometry(QtCore.QRect(110, 510, 131, 41))
        self.pushButtonGbyG.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 255);")
        self.pushButtonGbyG.setObjectName("pushButtonGbyG")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Võ Bích Ngọc K23111406"))
        self.pushButtonRefresh.setText(_translate("MainWindow", "Refresh Data"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add New Row"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete Row"))
        self.pushButtonSort.setText(_translate("MainWindow", "Sort By Price"))
        self.pushButtonGenerate.setText(_translate("MainWindow", "Generate Chart"))
        self.pushButtonAddUSD.setText(_translate("MainWindow", "USD"))
        self.pushButtonGbyG.setText(_translate("MainWindow", "Group "))
